# Generated by Django 4.2.28 on 2026-04-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0121_alter_estimate_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='page',
            index=models.Index(
                fields=['workspace', 'is_global'],
                name='page_workspace_is_global_idx',
            ),
        ),
    ]
